name: Check for uncommitted changes

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # This also ensures a rebuild matches the checked-in dist/ folder
  verify-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Read .nvmrc
        id: nvm
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Install NPM dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: npm run build

      - name: Compare the expected vs actual files.
        # Check everything, not just dist/ because anything not needing to be
        # committed should be listed in .gitignore
        run: test -z "$(git status --porcelain)"
